### ISSUE TITLE
Breaks when searching for "Zlatan Ibrahimović"

### ISSUE THREAD

**Issue by brodin** [luuse/spock#7]
Make sure to handle special chars.

**Comment by luuse** [comment]
The fetcher currently does not convert the input titles to the titles they use in the URLs. This means that we'll currently crash when we give the program the input "Zlatan Ibrahimović" however if you give it "Zlatan_Ibrahimović" it will be fine.

**Comment by brodin** [comment]
This is not true, Zlatan_Ibrahimović will not work, since it has special chars that breaks the url parser.

Solved by https://github.com/luuse/spock/commit/78ed5ee19b216c0a3cf59732cd9b2439758f511b

**Comment by luuse** [comment]
What's the error you're getting without that commit? I'm getting this:

    java.io.IOException: Illegal character in query at index 111: http://en.wikipedia.org/w/api.php?action=query&format=json&maxlag=5&prop=revisions&rvprop=content&titles=Zlatan Ibrahimović

Looking at index 111 in the URL it seems to be the space?

    http://en.wikipedia.org/w/api.php?action=query&format=json&maxlag=5&prop=revisions&rvprop=content&titles=Zlatan Ibrahimović

Wikipedia seems to treat `_` and `%20` about the same which I'm guessing is what `UrlEscapers` converts it to?

It still fails in the parsing step but that is due to other reasons?

**Comment by luuse** [comment]
Your fix for this is merged now.
